'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 提醒一下：这个版本最多只需要{0}就能正常运行 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_HighTips() As String
            Get
                Return ResourceManager.GetString("CheckVer.HighTips", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 提醒一下：这个版本最少需要{0}就能正常运行 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_LowTips() As String
            Get
                Return ResourceManager.GetString("CheckVer.LowTips", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你的版本过高！！这个NScript VBS脚本可能运行不正常 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_NotForceTooHigh() As String
            Get
                Return ResourceManager.GetString("CheckVer.NotForceTooHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你的版本过低！！这个NScript VBS脚本可能运行不正常 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_NotForceTooLow() As String
            Get
                Return ResourceManager.GetString("CheckVer.NotForceTooLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你的版本过高！！这个NScript VBS脚本最多需要{0}版本才能正常运行! 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_TooHigh() As String
            Get
                Return ResourceManager.GetString("CheckVer.TooHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 你的版本过低！！这个NScript VBS脚本最少需要{0}版本才能正常运行! 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CheckVer_Toolow() As String
            Get
                Return ResourceManager.GetString("CheckVer.Toolow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 错误：保留错误，错误代码：1 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x1() As String
            Get
                Return ResourceManager.GetString("Error0x1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 错误：内部错误，错误代码：2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x2() As String
            Get
                Return ResourceManager.GetString("Error0x2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 错误：不支持该方法，错误代码：3 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x3() As String
            Get
                Return ResourceManager.GetString("Error0x3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 错误：该方法已过时，错误代码：3 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x4() As String
            Get
                Return ResourceManager.GetString("Error0x4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已经运行了一个Game实例 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x5E() As String
            Get
                Return ResourceManager.GetString("Error0x5E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 NetScript.New方法不能被调用超过两次 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x6() As String
            Get
                Return ResourceManager.GetString("Error0x6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 NScriptGame没有初始化 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x7() As String
            Get
                Return ResourceManager.GetString("Error0x7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 NullReferenceException 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Error0x8() As String
            Get
                Return ResourceManager.GetString("Error0x8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 2.0 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property NiVerH() As String
            Get
                Return ResourceManager.GetString("NiVerH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 12898 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property NiVerL() As String
            Get
                Return ResourceManager.GetString("NiVerL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 2.4|控制台之way|2.0.2 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Ver() As String
            Get
                Return ResourceManager.GetString("Ver", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
